### ISSUE TITLE
CO2 Concentration

### ISSUE THREAD

**Issue by thompsoa** [JGCRI/gcam-core#113]
I'm not sure if I'm configuring the software incorrectly, or misinterpreting the outputs, but when I run the reference scenario in GCAM 5.2, or any scenario with the default historical emissions data I seem to get an incorrect CO2 concentration at the start of my simulation: in 2005 the concentration is 372.485 ppm but I believe it should be 379.850 ppm to match the scenarios I have looked up on IIASA databases (e.g. NGFS or AR5).  

![image](https://user-images.githubusercontent.com/67552748/89292864-ea9d5d80-d654-11ea-82b7-a16d4002e580.png)

**Comment by bpbond** [comment]
Hi @thompsoa - Hector (the simple carbon/climate model that runs using GCAM emissions to produce earth system predictions) is free running post-1750; by default it doesn't try to _exactly_ match the historical CO2 record. So yes, because it's not perfect, after 250 years it's a few ppm off the record.

It can do so, if the user defines a [model constraint](https://jgcri.github.io/hector/articles/manual/Constraints.html). This will force the model to run through historical [CO2] for example.

**Comment by thompsoa** [comment]
Thanks for that response @bpbond, I tried adding in the constraint to the .ini file but when I run GCAM I get the following error:

```
Wed Aug  5 11:54:45 2020:WARNING:Hector::Logger::printLogHeader: hector version 2.0
Wed Aug  5 11:54:45 2020:WARNING:Hector::Logger::printLogHeader: hector version 2.0
Exception: msg:         Could not parse var: CO2_constrain - Unknown variable name while parsing simpleNbox: CO2_constrain
func:   Hector::SimpleNbox::setData
file:   C:\gcam\gcam-core\cvs\objects\climate\source\hector\source\models\simpleNbox.cpp
ffile:  C:\gcam\gcam-core\cvs\objects\climate\source\hector\source\models\simpleNbox.cpp

line:   223
```

![image](https://user-images.githubusercontent.com/67552748/89409093-64971a80-d719-11ea-912a-02dbfb7d1e2f.png)

**Comment by bpbond** [comment]
Hmm, odd. As far as I know there's no reason the GCAM-coupled version of Hector can't accept a constraint, but... @pralitp ?

@thompsoa That file `co2_constrain.csv` exists in the directory I assume? Can you post it?

**Comment by thompsoa** [comment]
Ah, I've realised the variable should be Ca_constrain for my version of Hector. Seems to be working now.

**Comment by bpbond** [comment]
Great!
