### ISSUE TITLE
Representation of hydroelectricity in GCAM.

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#116]
Upon exploring the core XML files, I have 2 question about the representation of hydroelectricity in GCAM.
1. Why is hydroelectricity modeled as a fixed output and the shared weight for this technology set to zero? 
2. Why is hydroelectricity not represented in the Water Module of GCAM ? 

Thanks in advance.

**Comment by pkyle** [comment]
There are 3 questions here; I'll try to address them in order.
1a: Hydroelectricity has been modeled using `fixedOutput` since the early days of the model (MiniCAM) and is set up as such in order to reflect the relatively long construction times, government involvement, and other infrastructural considerations, as compared with other electricity generation technologies. There is an ongoing effort to improve the representation but it is not in the core model.
1b: `fixedOutput`subsectors and technologies are assigned a share-weight of zero because they are not included in the logit-based market sharing. The prescribed level of output is deducted from the whole sector's output and the market sharing is computed for the remaining elements within the nest.
2: Hydropower technologies are assigned "water consumption", intended to reflect the increased water evaporation from reservoirs as compared with the corresponding unenhanced water bodies, but are not assigned "water withdrawals" since technically operating a dam to generate power is considered a within-river use, and not a withdrawal. Due to the approach for representing hydropower production described above, there is no possibility to link region-level hydropower generation with basin-level water scarcity.

**Comment by RawisWar** [comment]
Thank you very much.
