### ISSUE TITLE
GCAM-USA: query "CO2 emissions by sector (no bio)" and LUC based CO2 emissions

### ISSUE THREAD

**Issue by sshreekar** [JGCRI/gcam-core#141]
I am facing two issues, First, I wanted to get state level biomass based negative emissions in GCAM-USA. Above query (CO2 emissions by sector (no bio)) in the GCAM-USA does not currently show the disaggregated negative emissions by technology. The query simply gives negative emissions at higher level like "base load generation". The query might need a modification to get that but the existing query seems quite complicated to follow through. A brief explanation on what the "xpath" in the query does would have been highly helpful.

Second, the query to get LUC based CO2 emissions in GCAM-USA does not provide LUC based CO2 emissions at the state level. Most likely it is because LUC are not yet disaggregated to the state level. Then, in GCAM-USA, LUC based CO2 emissions do not respond to the state level CO2 policies. I am not sure if this is doable but is there some way to make the LUC CO2 to respond to the state level CO2 policies?

**Comment by mbins** [comment]
Thank you for the questions.  The `CO2 emissions by sector (no bio)` does not work for GCAM-USA.  The xpath query assumes a certain market structure which is not true for GCAM-USA (where some technologies consume inputs from grid region or USA level markets in addition to state-level markets).  Additionally, as you observed, this query reports adjusted CO2 emissions by sector, not technology, for the core (32 region) GCAM.  Unfortunately, there is currently not a query to get biomass adjusted CO2 emissions by technology for GCAM-USA.  

Briefly, the `CO2 emissions by sector (no bio)` query operates as follows.  Biomass sequesters CO2 from the atmosphere as it grows (via photosynthesis).  GCAM reflects this sequestration as a negative emissions when biomass enters the energy system (in the regional biomass sector).  When biomass is transformed or combusted, the sequestered CO2 is re-emitted; these emissions are reflected in GCAM.  However, some users prefer to balance out this carbon sequestration and emissions for biomass.  The `CO2 emissions by sector (no bio)` query does this by resetting the negative emissions in the regional biomass sector to zero and re-allocating the negative emissions downstream to biomass technologies in the electricity and end-use sectors, offsetting the positive emissions from biomass consumption by those technologies.  Some of the biomass in GCAM is transformed into liquid, gaseous, or hydrogen fuels; the emissions of end-use technologies consuming these fuels are reduced to reflect the lower carbon content of those fuels based on the share of biomass feedstocks in producing that energy carrier.

You are correct that LUC based CO2 emissions are not available at the state-level in GCAM-USA because land use is not represented at the state-level.  You are also correct that LUC based CO2 emissions do not respond to the state level CO2 policies; unfortunately there is not a simple way to bridge this gap in regional resolution.  In principle CO2_LUC emissions in the USA region could be linked to a state-level emissions policy; however, this would imply state-level policies impacting land use (and associated emissions) for the entire USA.  Alternatively, the demand-adjust or price-adjust in the linked emissions policy for CO2_LUC (see http://jgcri.github.io/gcam-doc/policies.html) could be set to reflect a state's share of national land area, fraction of historical LUC emissions, etc.  This approach still requires careful interpretation - it applies a small policy signal to the entire USA land base, rather than the full policy signal to a fraction of the land base, and does not ensure that any resulting changes would be observed in the state with the emissions policy in place.
