### ISSUE TITLE
Trying to retrieve capital cost/O&M cost assumptions for technologies in GCAM v5.2

### ISSUE THREAD

**Issue by atmos-project** [JGCRI/gcam-core#155]
Hello,

I am in need of retrieving the capital cost/O&M cost assumptions for many technologies over time. I see those are in electricity.xml. However, I was wondering if there is another easier way to obtain these data. For example, through a .csv table in the gcamdata system? Do these assumptions change by regions? I think not but I would like to confirm.

Thanks for the attention.

**Comment by mbins** [comment]
Yes, capital cost/O&M cost assumptions are available as a .csv in the gcamdata system. 

If you've run the gcamdata driver (https://github.com/JGCRI/gcamdata/wiki/Driver) to build the xml files as well as intermediate output data tables, the best place to look is in `input/gcamdata/outputs`. 
Note, electricity has the numerical code `23`. The relevant tables for these cost assumptions will be L223.GlobalTechCapital_elec, L223.GlobalIntTechCapital_elec, L223.GlobalTechOMfixed_elec, L223.GlobalIntTechOMfixed_elec, L223.GlobalTechOMvar_elec, and L223.GlobalIntTechOMvar_elec.  Note that for each cost assumption, there are tables for standard (dispatchable) technologies (GlobalTech) and intermittent technologies (GlobalIntTech, such as PV and wind without dedicated storage). 

If you haven't run the gcamdata driver and the csv outputs tables aren't available, some information is also available in the `input/gcamdata/inst/extdata/energy` folder.  Again, electricity has the numerical code `23`, so you can check `A23.globaltech_capital.csv`.  You can also check them online and compare across versions such as from:
https://github.com/JGCRI/gcam-core/blob/gcam-v5.2/input/gcamdata/inst/extdata/energy/A23.globaltech_OMfixed.csv. One caveat is that the `A23.globaltech_` files only include historical values (along with parameters like improvement rate and maximum improvement that are used to extrapolate future costs).

Since GCAM 5.4, referencing the `A23` files has become a bit more complicated because we switched to getting power sector technology costs from the NREL ATB database such as `NREL_ATB_capital.csv`, and the old `A23.globaltech_` cost files are only used if users want to override the ATB cost for whatever reason.  Note that the `NREL_ATB_` files contain raw data to 2050, but those aren't necessarily the *exact* values used in GCAM because we fit the ATB costs to a functional form so we can extrapolate them to 2100.  In practice the values should be quite close, but it's best to use the processed values in the L223 tables which are exactly what's printed to electricity.xml.

Finally, you are correct that these assumptions are assumed to be the same across all regions.  If having heterogeneous regional costs/performance for power sector technologies is of interest, you could always implement that. However, you would have to set up the additional R processing required to do so.

**Comment by atmos-project** [comment]
Thanks.
