### ISSUE TITLE
CO2 policy add on file!

### ISSUE THREAD

**Issue by rsajedi** [JGCRI/gcam-core#16]
I try to run GCAM 4.3 in batch mode but still get just for reference scenario! 
Where should I put the batch file? I put it in exe and input folders, not working.
Any advise or resource?

**Comment by rplzzz** [comment]
There are a couple of changes you will need to make in the configuration file to get the batch mode to run.  The first line looks like this (in the stock configuration file):
```
		<Value name="BatchFileName">batch_ag.xml</Value>
```
Since your batch file is probably not called `batch_ag.xml`, you will need to change this file name to whatever you have named your batch file.

The second line you need to look at is this one:
```
		<Value name="BatchMode">0</Value>
```
A zero on this line causes the batch file to be ignored, and GCAM will run in normal mode.  You need to change the `0` to `1` for your batch to run.
