### ISSUE TITLE
Updating Input Data 

### ISSUE THREAD

**Issue by noc9498** [JGCRI/gcam-core#194]
I've been having some difficulty running GCAM under various GDP pathways. I've updated the file GCAM_3_GDP.csv in the folder \gcam-v5.4\input\gcamdata\inst\extdata\socioeconomics and then re-run the driver but it seems that the data system is not updating with the new input data. 

Am I doing anything wrong or is there something that I can do to fix this issue?

**Comment by atmos-project** [comment]
Before re-running the driver, are you making sure that you go to the "Build" menu in R studio and click  on "Install and Restart"?
Note: I am on Windows - I am not sure how these option appear in Mac.

**Comment by pkyle** [comment]
Yeah that's correct--also a quicker way to do that is to "Load All". There's probably a keyboard shortcut for it; on Mac/RStudio it's Command + Shift + L. It's also an option in the drop-down menu under the "Build" tab. In any case, the command in the console is:
```devtools::load_all(".")```
The difference between loading versus "Install and Restart" is that the latter also writes the package to disk, in the system folder where installed R packages are stored locally. Since there are some large data files in the package, that can take a while.

**Comment by noc9498** [comment]
Thanks, I followed those steps and it worked for me! I wasn’t clicking install and restart, or load all.
