### ISSUE TITLE
Solver restart within period 

### ISSUE THREAD

**Issue by michaeljaywalsh** [JGCRI/gcam-core#23]
@rplzzz & @pralitp 
This follows on an e-mail discussion I was having with Pralit a while back. 
I've found that when I've used 4.3 with multithreading (TBB), I can observe different solver tracks on different runs of identical inputs. This shows itself in two ways: (1) different numbers of iterations; (2) period solution failures would appear in one run by not the other. 

I've had to deal with my GCAM experiments regularly not solving some periods due to the solver getting stuck in situations were a region has very high supply and low demand, or **0** supply and reasonable demand. However, the failure is not consistent, as rerunning GCAM on the same input will sometimes successfully converge. This is telling me that there should be a global solution and GCAM can find the global solution, but for some reason is getting lost along the way.

In the absence of trying to figure out how to limit GCAM from getting sidetracked, It crossed my mind that restarting the solver in a given period (up to _n_ times), would exploit the multi-threading randomness to solve these periods that are prone to a meandering solver.  This is likely computationally expensive, and relies on the randomness of the TBB, but may be a useful brute force approach for dealing with some solver failures. Is there any way to reboot the solver in this manner using the solver configuration? Or will this require an edit to the source code?

**Comment by rplzzz** [comment]
@michaeljaywalsh Sorry for the slow reply; I've been pondering whether or not there is a way to do this without writing new code.  As it stands, I don't think it's possible to get any of the existing solver components to do this.  The issue is that all of the existing solver components treat any progress from the initial starting point as valuable, and so they never discard it.  What we would have to do is write a new solver component that monitors progress, and when it deems progress to have stalled it resets to the initial guess.

If we were to add such a component, I wouldn't want to rely solely on the nondeterminism induced by the multithreading to save the solution.  It's true that sometimes periods that failed to solve on one run might solve on another due to slightly different floating point results, but I wouldn't count on it as a method to recover stuck solutions.  What we should do in that case is to restart from a different initial guess.  One easy thing to do would be to disable or selectively disable the extrapolation procedure we use to generate the initial guesses (so that we would start from the last period's solution).  Another thing would be to go with some kind of blend of extrapolated guess and last-period guess.

I'll talk it over with the rest of the team and see if we can allocate some time to something like this.

**Comment by michaeljaywalsh** [comment]
Thanks for the response, no worries on the delay (I hope you enjoyed the long weekend).

Your proposed approach seems sound. On my end it has been continually heartbreaking to see results that would otherwise look continuous (as if they could be extrapolated) destroyed by one highly discontinuous market/period, that would work in another run, only to have another period/market fail. 

Again, since these periods/markets can be solvable, I'd hate to loose all the benefit of the extrapolation. Also, falling back on the last period's solution could be useful, but having more than 2 potential starting points (extrapolated and last period) to iterate over is necessary. Often, just rerunning once was all that was needed, but I think having the option to try several ball park initial guesses, would be useful. (i.e. setting _n_ number of attempts in the solver configuration)

I've been stalled on 2 DOE projects for several months now trying to figure out a way around these solver failures. Work I'm hoping to use as a basis for future work with JGCRI. Overcoming this would be a huge help for me.

**Comment by michaeljaywalsh** [comment]
If I were to take a stab at such an implementation, I'm thinking of adding a loop in the UserConfigurableSover that would rerun the whole period if the period fails for _n_ number of iterations set in the. Changes to the initial guess could then be set by expanding the Preconditioner to run different initial guesses on subsequent loops, either using a logic that is fixed or set in the solver configuration. Does that make sense? We can discuss more at the annual meeting, but I want to come in with a strategy to this.

**Comment by rplzzz** [comment]
That sounds plausible.
