### ISSUE TITLE
Residue biomass production returned no results in GCAM v6.0

### ISSUE THREAD

**Issue by Cermouth** [JGCRI/gcam-core#246]
Hello, I was trying to analyze biomass production and consumption in each region. In the GCAM model v5.4, there are data on purpose-grown biomass production, MSW production, and residue biomass production, in which the residue biomass is the major. While in v6.0, the residue biomass production returned no results. 
I also tried the "resource production" query but found that is also much smaller than the biomass production consumption. So is there any idea to have the results of regional biomass production? In my opinion, it should be of the same order. Thanks for any suggestions!

**Comment by EngFatemeh** [comment]
I tried this and it worked: 

This issue can be fixed by altering the query xPath. In Main_queries.xml you can change the existing query for residue biomass from

<supplyDemandQuery title="residue biomass production"> <axis1 name="sector">sector[@name]</axis1> <axis2 name="Year">physical-output[@vintage]</axis2> <xPath buildList="false" dataName="output" group="false" sumAll="false">*[@type='sector']//output-residue-biomass/physical-output/node()</xPath> <comments/> </supplyDemandQuery>

to
<supplyDemandQuery title="residue biomass production"> <axis1 name="sector">sector[@name]</axis1> <axis2 name="Year">physical-output[@vintage]</axis2> <xPath buildList="false" dataName="output" group="false" sumAll="false">*[@type='sector']//residue-biomass-production/physical-output/node()</xPath> <comments/> </supplyDemandQuery>

Please note the change from **output-residue-biomass** to **residue-biomass-production**.

**Comment by Cermouth** [comment]
@EngFatemeh Thank you so much! It worked.
