### ISSUE TITLE
Time steps change error in GCAM v6.0

### ISSUE THREAD

**Issue by bitzhz** [JGCRI/gcam-core#252]
Hi all,

I'm trying to change the base year (eg: from 2015 to 2010 ) of GCAM model, and modify the "Time constants" part of the constant.R file. However,  when I run the GCAM model, the error: 
"Period 3: 2010
Number of active state values: 3145261
ERROR:Base year demand: 0.485773 is greater than satiation level: 0.462917 " appeared and the 
model solution stopped.
And I couldn't find the satiation value of 0.462917 in the extdata file and don't know how to solve it.

Any advises or suggestions would be very helpful.

Best regards

**Comment by pkyle** [comment]
This happens when the calibrated demand in the final calibration year is greater than what we tell the model the satiation level for the service is. Unfortunately the code writing the error message doesn't know which region or service it is in. You should be able to find it in the `building_det.xml` file; I can't remember which one is written exactly in the XML file, so probably worth searching for both 0.4857 and 0.4629. What probably happened is, the satiation level was set based on 2015 historical data, but the energy consumption for the given service was higher in 2010 than in 2015, so the satiation value just needs to be increased. Just from searching these strings in a local workspace, it looks like it's probably `resid heating` in Russia.
There is a constant in `constants.R` called `energy.SATIATION_YEAR` that is intended to prevent this sort of thing from happening. I.e. it should be using the data from the final calibration year (2010 in this case) to assign the satiation levels. Anyway, whatever you can do to increase the satiation level above whatever the base-service was (in GJ per m2) in that final calibration year will solve the issue.

**Comment by bitzhz** [comment]
Hi @pkyle,

Thanks a lot for your kind advises. According to them, I increase all the satiation level values which are not satisfied with the calculated demand values, however, the calibaration faliure appeared in 2015 and solver failure showed in every period during 2020-2100. And I also look up the satiation level values in GCAM v5.2 xml file, and it seems like the same with that in GCAM v6.0. Maybe I need to do some calibration work instead of simply increasing them? Could you please give some details about how to calibrate the satiation level?

Best regards.
[main_log.txt](https://github.com/JGCRI/gcam-core/files/10046424/main_log.txt)
