### ISSUE TITLE
Cannot open include file: 'jni.h': 

### ISSUE THREAD

**Issue by zyqzxn** [JGCRI/gcam-core#32]
I am building the GCAM 4.4 on Windows 10 Machine. I used Microsoft Visual Studio 17.0 to build, and I have successfully installed the Java jdk-9.0.4. 
Now I was trying to run "Build Solution" from VS, and it gave me the error messages that:

"Hector::Logger::open': function does not take 3 arguments	objects-main	c:\work\duke\gcam4.4\cvs\objects\climate\source\hector_model.cpp	202	

Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\..\containers\source\single_scenario_runner.cpp)	objects-main	c:\work\duke\gcam4.4\cvs\objects\reporting\include\xml_db_outputter.h	54	

Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\..\containers\source\total_policy_cost_calculator.cpp)	objects-main	c:\work\duke\gcam4.4\cvs\objects\reporting\include\xml_db_outputter.h	54	
"

Any suggestion on how to solve this? Thanks!

**Comment by zyqzxn** [comment]
I solved the issues of "Cannot open include file: 'jni.h'" by changing the file "xml_db_outputter.h" from 
"“#include <jni.h>”"
to 
"“#include <C:/Program Files/Java/jdk-9.0.4/include/jni.h>”"

However, I still got the error messages that:
"Stoo few arguments in function call	objects-main	c:\Work\Duke\GCAM4.4\cvs\objects\climate\source\hector_model.cpp	202	

identifier "D_ANTHRO_EMISSIONS" is undefined	objects-main	c:\Work\Duke\GCAM4.4\cvs\objects\climate\source\hector_model.cpp	222	

member "h_exception::msg" (declared at line 34 of "c:\Work\Duke\GCAM4.4\cvs\objects\climate\source\hector\headers\h_exception.hpp") is inaccessible	objects-main	c:\Work\Duke\GCAM4.4\cvs\objects\climate\source\hector_model.cpp	557	"
"

Any help, please?

Thanks!

**Comment by pralitp** [comment]
> I solved the issues of "Cannot open include file: 'jni.h'" by changing the file "xml_db_outputter.h" from
"“#include <jni.h>”"
to
"“#include <C:/Program Files/Java/jdk-9.0.4/include/jni.h>”"

Two things.  Changing the include path include path to an absolute path is not good practice as it is not portable.  We recommend you use the approach described in the documentation:
http://jgcri.github.io/gcam-doc/gcam-build.html#23-java

More importantly GCAM does not currently run with Java 9.  We will have this fixed in our next release.  In the mean time we are asking users to downgrade to Java 8 or 7.

> However, I still got the error messages that:
"Stoo few arguments in function call	objects-main c:\Work\Duke\GCAM4.4\cvs\objects\climate\source\hector_model.cpp	202
>
> identifier "D_ANTHRO_EMISSIONS" is undefined	objects-main c:\Work\Duke\GCAM4.4\cvs\objects\climate\source\hector_model.cpp	222
>
>member "h_exception::msg" (declared at line 34 of "c:\Work\Duke\GCAM4.4\cvs\objects\climate\source\hector\headers\h_exception.hpp") is inaccessible objects-main	c:\Work\Duke\GCAM4.4\cvs\objects\climate\source\hector_model.cpp	557	"
"

It appears this has to do with using `hector 2.0`.  `GCAM 4.4` is still using `hector 1.1`.  We will be upgraded to `hector 2.0` in the next release of GCAM.  I presume you used the last method, direct download, for getting hector as described in:
http://jgcri.github.io/gcam-doc/gcam-build.html#3-compiling-hector

To get the correct version initializing the submodule (or using `make install_hector`) should still work.  If you really need the direct download this URL is now the appropriate link to get the `hector 1.1` version used in `GCAM 4.4`:
https://github.com/JGCRI/hector/archive/fd7a237424fd64063f905004d40f7641b9452112.zip
