### ISSUE TITLE
Defining region-specific technology cost

### ISSUE THREAD

**Issue by raditya101010** [JGCRI/gcam-core#368]
Hi All,

I am planning to run GCAM which will look into the future electricity generation mix constrained by the CO2 emissions-capped policy. I have read the GCAM tutorial presentation slide which says that "Much of the technology-level information is found in the global-technology-database, not in the technologies contained within each region". Does this mean that defining region-specific technology cost not possible? 

Is these perhaps any workaround? Maybe by adding 'addons' xml files?

Thanks!

**Comment by pkyle** [comment]
Region-specific deviations from the default values in the `global-technology-database` can be assigned by putting the information into the `stub-technology` objects located within each region. The stub-technology's values are used in the case of conflicts between the two (i.e., a cost specified within the stub-technology will over-ride the corresponding cost specified in the global technology database). The existing `electricity_water.xml` file already has stub-technology objects for the electric generation technologies, but there's generally only information read to the stub technologies in the model base years, where calibration values and calibration-year share-weights are assigned. Renewables have region-specific capacity factors indicated for all periods, so those have stub-technology information assigned to all periods.

**Comment by raditya101010** [comment]
> Region-specific deviations from the default values in the `global-technology-database` can be assigned by putting the information into the `stub-technology` objects located within each region. The stub-technology's values are used in the case of conflicts between the two (i.e., a cost specified within the stub-technology will over-ride the corresponding cost specified in the global technology database). The existing `electricity_water.xml` file already has stub-technology objects for the electric generation technologies, but there's generally only information read to the stub technologies in the model base years, where calibration values and calibration-year share-weights are assigned. Renewables have region-specific capacity factors indicated for all periods, so those have stub-technology information assigned to all periods.

Hi pkyle,

Thanks for the suggestion. I have tried to do so by including the information as seen below.
![Screenshot 2024-01-31 215948](https://github.com/JGCRI/gcam-core/assets/143774588/0530500f-f031-4175-b7d0-733dc5a20c9b)
However,  I ended up with this when trying to run GCAM. It seems the parsing failed resulting in the GCAM failing to commence
![Screenshot 2024-01-31 215918](https://github.com/JGCRI/gcam-core/assets/143774588/faa8a50b-4c50-4452-b1e6-126d1cdda87a)
Do you see any mistakes in putting the information (supplysector/subsector/stub-technology/)?

**Comment by pkyle** [comment]
Well, if your goal is to switch hydro from a `fixedOutput` technology to an endogenous one, there are a number of steps that ought to be performed including:
* re-set the share-weight from 0 to 1 at the subsector level and at the technology level
* assign a subsector share-weight interpolation rule (see other subsectors)
* move the historical calibration values (currently in `fixedOutput`) to `CalDataOutput/calOutputValue`
That's sort of the minimum set of steps, but really to do endogenous hydro you'll also need to assign a supply curve that characterizes the scarcity of the resources in the region, capturing (1) the increase in the levelized costs of electricity generation as a function of deployment, and (2) the limits on the deployment. See e.g. the representation of geothermal for a simple bounded supply curve which is read in as an input to a technology.

**Comment by raditya101010** [comment]
Hi pkyle,

Thanks for the swift response, and the suggestions. 

I didn't really aim at switching hydro to be an endogenous. Rather, relevant the main question here, the goal is to include a different technological costs (not just for hydro, but for all generation technologies, both RE and non-RE) than the ones used in the global database. The costs I intended to use are tailored specifically for the region of Indonesia.

In the case of hydro, I have tried to leave everything as default and add the information on the costs only to each year. But, the simulation still wouldn't start. Does this mean that the fixedOutput is incompatible with the redefinition of the technology cost?

**Comment by pkyle** [comment]
I can't promise that this is why the model crashed (didn't seem to leave an error message), but the use of `fixedOutput` is incompatible with tracking of costs. Fixed output technologies should have share-weights of zero, and they aren't included in any logit share or price calculations. They do not contribute to the weighted average price of their parent sector (commodity). The model possibly got jammed up trying to track the capital investment of a fixedOutput technology.
I don't really know what to recommend because I don't know what the aim is here. If you're just trying to estimate the capital investment into hydro from the scenario, that could be computed post-hoc based on the assumed fixed output, along with assumptions about survival curves, the ages of existing assets, and capacity factors. If you want the model to have hydro as an endogenous choice, I don't really see how to get reasonable results without some sort of supply curve, but you could just try it and see. If you're OK with just holding the 2015 output constant going forward, you can assign a long lifetime and then set the share-weight to zero in future periods, starting in 2020. But there's no way to exogenously fix the output of a technology while still tracking its costs in the model.

**Comment by raditya101010** [comment]
Okay. Thanks Page for your explanation!

Yes, the aim is to make hydro to be an endogenous choice. I will try to adjust the supply curve and let's see how it goes.
