### ISSUE TITLE
Resource production CO2 emissions & CO2 emissions by sector

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#385]
Hi GCAM team! 

I have 2 clarifying questions on CO2 emissions in the model.

**Q1: query `CO2 emissions by resource production`**
These emissions are upstream emissions for primary energy resources. My understanding is that they are not included in the carbon coefficient of fuel (which can be found in` A_PrimaryFuelCCoef.csv`).

According to the document, "fugitive CO2 emissions" is part of the resource production emissions. But I didn't find other sources related to resource production emissions. Are there any other emissions also included in the resource production stage? Does fugitive CO2 emissions = resource production emissions？

**Q2: query `CO2 emissions by subsector (excluding resource production)`**

Are the emissions calculated by multiplying the carbon coefficient in ` A_PrimaryFuelCCoef.csv` and inputs for this sector?
Using "H2 central production" as an example:

![302064907-3190914e-0194-4a52-8f8b-44eb9b182358](https://github.com/JGCRI/gcam-core/assets/156739336/b9cca2fe-9a19-4f5d-8918-58d712fb3b49)
![Screenshot 2024-02-03 172645](https://github.com/JGCRI/gcam-core/assets/156739336/90e204bb-2439-4bef-8edd-07f893168536)

23 * 0.162+0.002 * 14.2+0.648 * 14.2=12.956 MTC
(23 and 14.2 are carbon coefficients for biomass and natural gas respectively)
Numbers seem to match the CO2 output but a little bit different. Maybe because of the rounding issues or I might miss anything.

One thing I am confused about -  there is also water electrolysis H2 but the emissions of electricity seem not included. There is no subsector named "electricity" in the `CO2 emissions by subsector (excluding resource production)`.

Any guidance would be appreciated!! Thanks so much!

**Comment by pkyle** [comment]
Re: (1), starting with v7 GCAM includes fugitive CO2 emissions from fossil resource production. This includes venting, flaring, and any other passive CO2 emissions e.g. from abandoned facilities, but it excludes any energy-related emissions. The energy consumption for coal mining (EMINES), and for oil and gas exploration and production (EOILGASEX) are mapped to other industrial energy use, as indicated in `energy/mappingsIEA_flow_sector.csv`.
Re: (2), yes the emissions are calculated as the sum of each input-output coefficient times the carbon content of the input commodity, minus the carbon content of the output fuel (if it's non-zero), times (1 minus the CO2 removal fraction) for any technology with CCS. So, the calculation is simpler for end-use sectors and for electricity and hydrogen than it is for carbon-containing fuels (refining, gas processing, etc). And it's simpler for technologies that don't have CCS. The reason water electrolysis doesn't have any reported CO2 emissions is that the carbon content of electricity is zero; the CO2 emissions from producing electricity are tracked in the electric power sector. Note that in this reporting scheme, biomass is assigned a carbon content, which differs from standard emissions reporting practices. It is done so as to physically track the carbon in biomass so that it can be sequestered by BECCS; the carbon emissions from biomass use are counter-balanced by atmospheric CO2 uptake in the biomass production sectors which report negative emissions (`regional biomass`, `regional corn for ethanol`, `regional sugar for ethanol`, `regional biomass Oil`). The queries with `(no bio)` in their names perform a series of extra steps to remove any biomass-derived carbon from reported CO2 emissions.

**Comment by Youyi77** [comment]
Hi Page @pkyle,

Many thanks as always! Also big thanks for the additional biomass explanation as well, very helpful.

I misunderstood the CarbonCoef. I used to think the carbon coefficient = emission coefficients. But it actually means the carbon content. Regarding your comments, I am still a bit confused about the following:

**Q1:** You mentioned the carbon content examples about the output “fuels”. How about manufacturing sectors where the outputs are not fuels but commodities like steel, cement, aluminum etc. So we need to deduct the carbon content embodied in steel/cement/etc to get total CO2 emissions in their sectors. I looked carefully for CarbonCoef for those outputs but failed. Could you please share any insights on this? 

**Q2**: For transportation sectors, can we consider all the energy inputs consumed to provide transportation services and there aren’t any other outputs generated that contain carbon? So the total CO2 emissions of the transportation sector is the CarbonCoef in any input fuel* how much fuel is consumed.

**Q3**: “The electricity for H2 production considered to be zero” seems like a system perspective to avoid double counting. So the electricity (regarding the grid electricity mix, not solar/wind electricity) used for electrolysis is recorded as zero but actually, there are still emissions associated with it. (If I am understanding it correctly.)

Therefore, if I want to calculate the total carbon emissions of H2 central production, it makes sense to add back the CO2 emissions (calculated by the below formula) associated with the grid electricity mix under any given scenario?

_Electricity supply mix emission intensity * electricity inputs for H2 production_

where the electricity supply mix emission intensity = CO2 emissions of total electricity generation/total electricity generation

Thanks so much!

**Comment by pkyle** [comment]
(1) What is deduced in that calculation is the physical carbon in the output commodity. For simplicity we assume the carbon content of steel is zero (in reality steel is something like 0.5% carbon; again we don't worry about. that). Same for aluminum, cement, ammonia, etc. As an alternative example, in the refining sector, the output commodity has a carbon content of 19.6 kgC per GJ of fuels produced. To estimate the emissions from any production technology, that carbon needs to be deducted from the sum of the input carbon to estimate the net emissions.
(2) Yes, for transportation, the emissions will be equal to the carbon content of the input fuel multiplied by the ratio between the input fuel and the output of the technology, which is indicated in million passenger or million tonne-km. There are some hard-wired unit conversions in transportation; the reported input-output coefficient is in btu per vehicle-km, whereas the relevant ratio here is EJ per million pass-km.
(3) For attribution of "upstream" emissions to any end use, yes you can compute the average emissions intensity of electricity, and use that as the carbon content of the electricity input to the grid electrolysis technologies of the hydrogen sectors. This would be done in post-processing and wouldn't change anything in the model or its output. For that calculation, I normally query the CO2 emissions by subsector or technology so that I can manually zero out the reported emissions coming from the biomass technologies, and then for the denominator, I add up the outputs of elect_td_bld, elect_td_ind, and elect_td_trn. That way the estimated average carbon intensity takes into account the own-use and T&D losses. Note that the method I described includes rooftop PV in the denominator, which might or might not be wanted, and doesn't assign any emissions to the numerator from cogenerated electricity in the industrial sector.

**Comment by Youyi77** [comment]
Hi Page! Got it! Thank you so much. These really help clear out all my confusion! Very helpful.
