### ISSUE TITLE
Building-equipment stock tracking in GCAM v7 (cross-post from gcamdata)

### ISSUE THREAD

**Issue by dobrien13** [JGCRI/gcam-core#390]
Good morning GCAM team,

In the past, my team has updated the GCAM data system packaged with GCAM v6 to add retirement curves to building technologies so that when we applied sales standards to new technologies, we wouldn't replace the entire fleet. To do so, we added in an A44.globaltech_retirement.csv file and modified zchunk_batch_building_det_xml.R and zchunk_L244.building_det.R to incorporate stock retirement profiles.

Now, while updating to v7, I see that building_det.xml has tracking of capital with depreciation attached to building technologies, added through the 244.GlobalTechTrackCapital_bld chunk, if I'm understanding correctly. If I wanted to add in a retirement profile to technologies, would I need to make any changes to how the capital is tracked or could I add the building tech retirement changes without crossing any wires?

Thanks for any info!
DJO

**Comment by pkyle** [comment]
Your existing method of adding retirement functions won't be impacted by this change, which is just used for backing out the capital investment in the buildings sector from the model's output, for the macro model. In the standard default configuration the macro model is not enabled. You can check this in the Bools section of the configuration file:
```
		<Value name="FixedGDP-Path">1</Value>
```
Where FixedGDP-Path indicates to use the exogenously specified GDP path instead of the macro module.

**Comment by dobrien13** [comment]
Great, that makes sense. Thanks for the clarification, @pkyle. 

Hope your week goes well.
