### ISSUE TITLE
GCAM V4.4: "Could not find scenarios to run." With Batch query mode enabled.

### ISSUE THREAD

**Issue by Inorman500** [JGCRI/gcam-core#41]
In the XMLDB Driver properties I set in-memory database to True and pointed "Batch queries" to Gcam's XMLdb batch query file. 

 When Gcam is done running I get this message:
Running headless? true
About to perform query: collection()/scenario
java.lang.Exception: Could not find scenarios to run.
        at ModelInterface.ModelGUI2.DbViewer.runBatch(DbViewer.java:1872)
        at ModelInterface.InterfaceMain.runBatch(InterfaceMain.java:650)
        at ModelInterface.InterfaceMain.main(InterfaceMain.java:206)
        at RunQueries.run(RunQueries.java:127)
        at java.lang.Thread.run(Unknown Source)

For reference:
Gcam Version: 4.4
Java version: 1.8
OS: Windows 10

Any advice? Thanks

**Comment by rjplevin** [comment]
Hi, Ivan. There's a bug in ModelInterface.jar in v4.4 that prevents this from working. The bug is fixed in GCAM v5.1, so you can copy its ModelInterface.jar over the one in v4.4 to resolve this problem.

Note that in 5.1, the file is in output/modelinterface/ModelInterface.jar. Copy this to your v4.4 workspace in input/gcam-data-system/_common/ModelInterface/src/ModelInterface.jar.

Cheers,
Rich

===============================
Richard Plevin, PhD
Transportation Sustainability Research Center
Institute of Transportation Studies
University of California, Berkeley
510.575.9515
http://plevin.berkeley.edu

**Comment by rjplevin** [comment]
The bug in the 4.4 MI was that it was closing the database after the first query. It worked for single queries. I recommend ensuring that individual queries work the way you expect. If your individual queries run, they should run as a batch with the updated jar file. (I gave a workshop last week in which we solved the 4.4 MI problem the way I described. The query would also fail if you copied the jar file to the wrong place, or if the name of the scenario doesn't match what's in the database.

-Rich

===============================
Richard Plevin, PhD
Transportation Sustainability Research Center
Institute of Transportation Studies
University of California, Berkeley
510.575.9515
http://plevin.berkeley.edu

**Comment by pralitp** [comment]
Note, we have just released GCAM 4.4.1 which is a bug fix release for 4.4 where we have back ported the Java components fixes @rjplevin mentioned.  Could you try download that version and seeing if you have better luck?
