### ISSUE TITLE
Unable to create biofuel target policy

### ISSUE THREAD

**Issue by pallavidas29** [JGCRI/gcam-core#414]
I am trying to create biofuel policy target of 25% in refined liquids enduse using the existing example in the documentation. However, I am unable to meet my biofuel target. The generation of biofuel credits from the 4 technologies is not equal to their refining output even when i have kept the output ratio as 1. It is, in fact, lower. The biofuel credits generated have zero cost from the prices of all market query. On the demand side though, refined liquids end use shows 25% demand for bio fuel credits from the demand of all markets query. Can someone please help me create this target correctly. Thank you very much. 

[Biofuel.docx](https://github.com/JGCRI/gcam-core/files/14931807/Biofuel.docx)

**Comment by licaicaicumt** [comment]
How did you solve this problem? I'm going to set up policies related to biomass energy, and any suggestions will be helpful to me. Thanks！

**Comment by pkyle** [comment]
I don't know specifically what the issue was in the original comment, but when running these sorts of policies I typically disable vintaging of all technologies in the relevant sector(s) by setting the technology lifetimes to 5. Otherwise you'll have capital carryover from prior years interfering with the credit market.
