### ISSUE TITLE
hydrogen cogen interpretation

### ISSUE THREAD

**Issue by Youyi77** [JGCRI/gcam-core#419]
Hi GCAM team, 

I have some Qs related to the "hydrogen cogen" under other industrial energy use. My understanding - it represents the H2 used for the cogeneration of heat and electricity.

Background setting: no policy/carbon target setting, just run scenarios with a low carbon price $0.01/ton (to include CCS technologies)

**Trial 1:** give high subsidies to some H2 production techs to make the H2 very cheap. Most H2 was consumed by the "hydrogen cogen" in the other industrial energy use sector. So this sector (specifically hydrogen cogen) is competitive in consuming H2. 

**Trial 2:** give high subsidies + close the tunnel for H2 supply to `other industrial energy use`. After cutting down the H2 supply for other industrial energy use, the total H2 produced dropped sharply. There aren't many changes in H2 consumption for the rest of the end-use sectors. 

That is to say, if there is abundant cheap H2 in the market, it seems to be finally only consumed by `other industrial energy use`. The ability to receive extra H2 from other end-use sectors seems saturated even though there are cheap H2 available. 

Trying to reconcile:

- Unlike other end-use sectors, `other industrial energy use` does not have a demand cap. So it will receive H2 as long as it is cost-competitive. If there are cheap fuels, the other industrial energy use sector will be a huge energy consumer?

- Also, the H2 consumed in the rest of H2-related sectors is determined by logit, mostly relative logit function, which prevents the winner-take-all situation.

Greatly appreciate any ideas on these! Thanks so much.

**Comment by pkyle** [comment]
This is a strange issue that we haven't fully figured out, though the next release of GCAM will have a patch. The cause is an apparently significant disconnect in the assumed costs of biomass gasification between the power sector and the hydrogen sector. The power sector's costs are based on the 2019 Annual Technology Baseline put together by NREL. https://atb.nrel.gov/archive
The hydrogen sector's costs are based on NREL's H2A model https://www.nrel.gov/hydrogen/h2a-production-models.html
For some reason the biomass gasification process is much cheaper in the hydrogen sector, and to such an extent that this strange outcome is observed in the results in low-carbon scenarios. What's happening in low-carbon scenarios in GCAM versions 6 and 7 is that hydrogen for industrial combined heat and power is allowing cost-effective BECCS. I don't know the reasons for the disconnect in the costs between the ATB and H2A, but it's not a result I consider to be valid/reliable.

**Comment by Youyi77** [comment]
Hi Page! Thanks so much for your quick response!

I get your words but still have some difficulties in understanding - why the price difference of **biomass gasification** between H2 sector & electricity sector affects the other industrial energy use sector.

I am just thinking lowering costs of no matter which H2 production tech would result a lower h2 supply prices. So the cost of `hydrogen cogen` is low, then it is favorable? (a large market here without any upper limit)

When the hydrogen supply price on the market is very low, I go back and check the cost of technology `hydrogen cogen` in `other industrial energy use` sector, it is significantly lower than its competing the technology `hydrogen` . So the `hydrogen cogen` is of course very competitive in consuming H2.

But compared to `hydrogen`,  the efficiency of `hydrogen cogen` is lower, the non-energy costs are higher, while the energy costs are roughly the same, it’s counterintuitive why `hydrogen cogen` has lower costs. Maybe it is related to `hydrogen cogen`'s secondary output (electricity)? Are there any credits given back to `hydrogen cogen` to make it cost cheaper? or is there any link between this secondary output (electricity) & electricity sector? (Here is my main confusion)

**Comment by whitenightZhang** [comment]
I understand your question. According to my understanding, in the GCAM version, the reason for higher usage of hydrogen cogen in "other industry energy use" is because the electricity it produces acts as a "subsidy" to the existing technologies. This leads to a disproportionately high usage of hydrogen cogen.

**Comment by pkyle** [comment]
Thanks @whitenightZhang, and both of you are correct. I wasn't as clear as I could have been in my reply. The `hydrogen cogen` technology in the current release versions of GCAM is parameterized as a fuel cell that produces power and heat in reasonably similar quantities. The total cost of the technology is calculated as (exogenous) non-energy costs, plus fuel costs (equal to endogenous fuel prices times exogenous input-output coefficients), minus any secondary output revenue (electricity price times electricity secondary-output coefficient).
In low-emissions scenarios, electricity prices are increasing more than hydrogen, because GCAM has comparatively cheap BECCS in the hydrogen sector. As such, most hydrogen is produced from biomass with CCS, whereas electricity tends to be produced primarily from wind, solar, and natural gas with CCS, with only a small contribution from biomass CCS. The discrepancy in BECCS costs between the electricity and hydrogen sectors is so large that if GCAM included a "hydrogen CC" (i.e., hydrogen combined cycle) technology in the power sector, whose non-fuel cost and energy intensity was set equal to natural gas combined cycle with CCS, the indirect biomass -> hydrogen (with CCS) -> electricity (CC) pathway would be much cheaper (~40% less) than the current direct ("integrated") pathway: biomass -> electricity (IGCC with CCS).
I suspect that the discrepancy is because the ATB (used for the power sector) is based on real-world conditions, as there has been some relevant industry experience, whereas the H2A approach for estimating costs is more bottom-up, because there is limited/zero real-world experience with the technology. In any case, it is a topic that we are monitoring, and revised biomass-to-hydrogen assumptions will certainly be in the next GCAM release. Subsequent revisions will probably continue in the next few years, reflecting the available information at the time.

**Comment by Youyi77** [comment]
Hi @whitenightZhang @pkyle Thanks so much for the detailed explanation! I think the biomass-related issues make sense to me now! Really appreciate it. 

Page's scenario (low-carbon one) -  the model solves for different tech mix production for H2 & electricity. So the induced `hydrogen cogen` doesn't necessarily have to be cheap in an absolute value but cheaper than its counterpart electricity production tech.

My scenario is manually making H2 cheaper by giving high subsidies. So it is both cheaper in an absolute term and a relative term.

But two scenarios lead to the same situation where H2-produced electricity is cheaper than some primary electricity production techs.

Just a quick follow-up - I think the electricity cost (all the primary electricity production pathways) doesn't include the revenue from electricity production. But why the revenues are accounted for costs of `cogen` techs?  It sounds a bit inconsistent?

**Comment by whitenightZhang** [comment]
@Youyi77 In fact, I believe that the balance of supply and demand in electricity actually includes the impact of electricity prices on power supply, but it uniformly affects all generation technologies. In hydrogen cogeneration, other non-cogeneration technologies cannot provide electricity, so they are at a disadvantage in the competition.

**Comment by Youyi77** [comment]
@whitenightZhang Thanks for the comment! I totally agree with your last sentence on the competition within the `other industrial energy use` sector.
But if we look at the power sector, all electricity production compete with each other based on the costs (energy costs + non-energy costs + carbon penalties but no revenue considered here). Then I am assuming the `cogen` techs will join this competition? (or maybe not..) But `cogen` techs costs do consider the revenue earned back, which makes the `cogen` techs cheaper (under some scenarios at least) compared with other primary electricity production techs. So I am wondering why for `cogen` techs, the revenue is considered in the cost.

**Comment by whitenightZhang** [comment]
@Youyi77 I can understand your question, and my previous example placed cogeneration technology in the context of competing heating technologies. My thinking is that the same logic should apply if placed in the context of competing power generation technologies. Cogeneration technology produces heat as well as power, which also brings benefits, giving it an advantage in competition with other power generation technologies. I'm not sure if my understanding is correct.

**Comment by pkyle** [comment]
This just gets into the question of which output is "primary" as opposed to "secondary" when a technology produces multiple outputs. It is arbitrary; cogen technologies could be placed in the `electricity` sector and receive secondary output revenues from the heat produced, or in the industrial sector, receiving secondary output revenues from the electricity produced. Both paradigms are used. The `electricity` sector is understood to be technologies whose primary purpose is electricity productionm, and it actually includes the MAINCHP facilities in the IEA energy balances. In selected regions where heat is modeled as an energy commodity, some electric generation technologies have a secondary output of `district heat`. GCAM's industrial sector cogen is from the IEA's AUTOCHP, defined as facilities whose primary purpose is to supply heat/power for on-site operations. Here, the primary output is industrial energy use, and the secondary output is electricity.
Anyways there also seems to be some confusion about how revenues are handled in these cost calculations. The revenue of the primary output of a technology is not considered in the cost calculation, for the simple reason that the cost calculation is estimating costs, not profit rates. However, for technologies with multiple outputs, costs are still represented per unit of the primary output, but to accurately represent this, the revenues from any secondary outputs need to be deducted.

**Comment by Youyi77** [comment]
Hi @whitenightZhang @pkyle Thanks so much for the clarifications! These are very helpful. Learned a lot!!!
