### ISSUE TITLE
net terrestrial C uptake in GCAM

### ISSUE THREAD

**Issue by RuiSu-gif** [JGCRI/gcam-core#444]
Dear GCAM Team,
﻿
I am a new user of the GCAM model, and I have a few questions regarding the net terrestrial carbon (C) uptake in GCAM.
﻿
I am not sure about the source or calculation principles behind the net terrestrial C uptake in GCAM. Could you please provide some information on this? Are there region-specific values available for net terrestrial C uptake?
Is it possible to modify the carbon sequestration for a specific region under different scenarios? If so, how can I achieve this?
I would greatly appreciate any guidance or suggestions you can provide.

**Comment by pkyle** [comment]
The simple carbon cycle model within GCAM is documented at https://jgcri.github.io/gcam-doc/land.html
Note that this is different from the carbon cycle model that is part of Hector, documented at https://jgcri.github.io/gcam-doc/hector.html, which is only resolved at the global level, in which is not used for the reported terrestrial emissions or sequestration from the land system in a GCAM model run.
Despite the name "simple," this is one of the most difficult parts of the model for a user to modify in such a way as to achieve some desired result. The net reported emissions or sequestration, for any region and model time period, is dependent on all of the land use decisions that have been made up until that time period, considering the average vegetation and soil carbon densities of each modeled land-use type. Because the average carbon densities of each land-use type are assumed time-invariant (e.g., the maximum vegetation carbon density of a tropical rainforest is 120 tC/ha, or 12 kgC/m2), a user can't just increase assumed carbon densities going into the future in order to represent enhanced uptake.
Just as a final note here, the reported net emissions in sequestration make the most sense when reported by region, or alternatively by basin within a model region. The data are also written out by land-use type, the note there any reported changes over time reflect changes in the land area of the given land use type. For example, a scenario with an expansion of crop land into forest will report net emissions at the region or basin level, but will report net sequestration by the crop land land use types. This is just because the total stock of carbon in cropland is increasing as the land area increases.

**Comment by RuiSu-gif** [comment]
Thank you for your kind and detailed reply. It really helps me.

**Comment by RuiSu-gif** [comment]
> The simple carbon cycle model within GCAM is documented at https://jgcri.github.io/gcam-doc/land.htmlGCAM 中的简单碳循环模型记录在 https://jgcri.github.io/gcam-doc/land.html Note that this is different from the carbon cycle model that is part of Hector, documented at https://jgcri.github.io/gcam-doc/hector.html, which is only resolved at the global level, in which is not used for the reported terrestrial emissions or sequestration from the land system in a GCAM model run. 请注意，这与 Hector 的碳循环模型不同，该模型记录于 https://jgcri.github.io/gcam-doc/hector.html，该模型仅在全球级别上解决，其中未使用用于 GCAM 模型运行中报告的陆地排放或土地系统封存。 Despite the name "simple," this is one of the most difficult parts of the model for a user to modify in such a way as to achieve some desired result. The net reported emissions or sequestration, for any region and model time period, is dependent on all of the land use decisions that have been made up until that time period, considering the average vegetation and soil carbon densities of each modeled land-use type. Because the average carbon densities of each land-use type are assumed time-invariant (e.g., the maximum vegetation carbon density of a tropical rainforest is 120 tC/ha, or 12 kgC/m2), a user can't just increase assumed carbon densities going into the future in order to represent enhanced uptake. 尽管名称为“简单”，但对于用户来说，这是模型中最难修改的部分之一，以实现某些所需的结果。对于任何区域和模型时间段，报告的净排放量或封存量取决于该时间段之前做出的所有土地利用决策，并考虑每种模拟土地利用类型的平均植被和土壤碳密度。由于假设每种土地利用类型的平均碳密度不随时间变化（例如，热带雨林的最大植被碳密度为 120 tC/ha，或 12 kgC/m2），因此用户不能仅仅增加假设的碳未来的密度以代表增强的吸收。 Just as a final note here, the reported net emissions in sequestration make the most sense when reported by region, or alternatively by basin within a model region. The data are also written out by land-use type, the note there any reported changes over time reflect changes in the land area of the given land use type. For example, a scenario with an expansion of crop land into forest will report net emissions at the region or basin level, but will report net sequestration by the crop land land use types. This is just because the total stock of carbon in cropland is increasing as the land area increases. 正如这里的最后一点，报告的封存净排放量在按区域或模型区域内的流域报告时最有意义。数据还按土地利用类型列出，并注明随时间报告的任何变化都反映了给定土地利用类型的土地面积的变化。例如，农田扩大为森林的情景将报告区域或流域层面的净排放量，但将报告农田土地利用类型的净封存量。这只是因为农田的碳总储量随着土地面积的增加而增加。

Based on my understanding of the GCAM and Hector documentation, the land_use_emission result in GCAM corresponds to Hector's land_use_emission-land_use_uptake. This implies that the CO2_emission_by_region in GCAM does not include NEP (Net Ecosystem Production) = NPP (Net Primary Production) - RH (Respiration of Heterotrophs). Therefore, to achieve changes in carbon sinks, it is necessary to modify NBP_constrain (NBP = NPP - RH - land_use_emission + land_use_uptake) in the Hector model. 
﻿
If there are any inaccuracies, pls let me know!

**Comment by RuiSu-gif** [comment]
> The simple carbon cycle model within GCAM is documented at https://jgcri.github.io/gcam-doc/land.html Note that this is different from the carbon cycle model that is part of Hector, documented at https://jgcri.github.io/gcam-doc/hector.html, which is only resolved at the global level, in which is not used for the reported terrestrial emissions or sequestration from the land system in a GCAM model run. Despite the name "simple," this is one of the most difficult parts of the model for a user to modify in such a way as to achieve some desired result. The net reported emissions or sequestration, for any region and model time period, is dependent on all of the land use decisions that have been made up until that time period, considering the average vegetation and soil carbon densities of each modeled land-use type. Because the average carbon densities of each land-use type are assumed time-invariant (e.g., the maximum vegetation carbon density of a tropical rainforest is 120 tC/ha, or 12 kgC/m2), a user can't just increase assumed carbon densities going into the future in order to represent enhanced uptake. Just as a final note here, the reported net emissions in sequestration make the most sense when reported by region, or alternatively by basin within a model region. The data are also written out by land-use type, the note there any reported changes over time reflect changes in the land area of the given land use type. For example, a scenario with an expansion of crop land into forest will report net emissions at the region or basin level, but will report net sequestration by the crop land land use types. This is just because the total stock of carbon in cropland is increasing as the land area increases.

Based on my understanding of the GCAM and Hector documentation, the land_use_emission in GCAM corresponds to Hector's land_use_emission-land_use_uptake. This implies that the (CO2_emission_by_region+LUC emissions by region) in GCAM does not include NEP (Net Ecosystem Production) = NPP (Net Primary Production) - RH (Respiration of Heterotrophs). Therefore, to achieve changes in carbon sinks, it is necessary to modify NBP_constrain (NBP = NPP - RH - land_use_emission + land_use_uptake) in the Hector model.
﻿
If there are any inaccuracies, pls let me know!
