### ISSUE TITLE
Food demand nesting structure Fig not displaying in the doc?

### ISSUE THREAD

**Issue by jiangyongye** [JGCRI/gcam-core#467]
I noticed that the Food demand nesting structure is not displayed in the doc. Is that a bug? 
![1726190935294](https://github.com/user-attachments/assets/8941465e-4a16-49d9-83ab-36448d933349)

**Comment by pkyle** [comment]
OK this is pretty subtle but thanks for flagging! @pralitp the issue is that this link, in `demand_land.md`, is for `FoodNests.png` while the file is called `Foodnests.png`. We'll get it fixed when we can but in the mean time here's a direct link to the figure https://github.com/JGCRI/gcam-doc/blob/gh-pages/gcam-figs/Foodnests.png

**Comment by jiangyongye** [comment]
Thanks for the quick help, Kyle!
