### ISSUE TITLE
Forcing coal retirements

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#61]
Hello,

Does anyone have experience implementing a policy that forces coal retirement in GCAM? I see this is done in GCAM-USA and am wondering if there is a policy XML file to achieve this in the global version of GCAM.

Thank you.

**Comment by d3y419** [comment]
GCAM will economically retire coal under sufficiently high carbon price. This is specified in profit-shutdown-decider in the input file.

If you want to explicitly retire just coal (power), but not other emissions, you could also reduce the lifetime and/or half-life of existing coal plants.

Fyi, the Global Coal team at UMD has been working on a global unit-by-unit retirement analysis for coal power. You can read about it here: http://stateofglobalcoal.org/report-download/ ( @rynacui leads the project )

**Comment by pkyle** [comment]
Just in case it helps, to modify the retirement function in all regions you can make changes to the following file and re-build XMLs: `input/gcamdata/inst/extdata/energy/A23.globaltech_retirement.csv`
The `lifetime` column indicates the maximum number of years that the plants will operate. Where the `year` is equal to `final-calibration-year`, the value you read in will be applied to the 2010 cohort only. The `initial-future-year` values will be written to all future years.

**Comment by robbieorvis** [comment]
Thank you both for your quick replies!

Just so I'm clear, there is no way to force retirements (let's say a government has an early shutdown policy, which I'm trying to model) other than by changing the lifetimes?

One idea I had was to generate a tax of some kind to make them more uneconomic and force retirement, but I'm not sure if this is possible.

Also, could you confirm that once built, power plants generate at the same level unless they retire? (i.e. there is no dispatch model so to speak, it is just assumed that generation continues to produce at the built level until it retires)?

Thanks again.

**Comment by d3y419** [comment]
A "coal tax" method works, but it has some issues. I have a sample input I can send, email me your address at hmcjeon at pnnl. (Can't attach xml files on github).

The issue is that this makes not only coal really expensive, but all electricity very expensive. As a side effect, there's going to be some sort of "reverse-electrification" happening in end uses. This needs to be resolved by offsetting the "coal tax" at the electricity consumption in end uses.

Power plants, once built, generate at the same level unless they retire or shutdown. There's a development version for dispatch modeling, but it has not been committed to the core GCAM yet.

**Comment by pkyle** [comment]
There are three ways by which early retirement/shutdown can be represented:
1) changing the `lifetime`, i.e. the maximum lifetime. This is the simplest to implement, and has minimal equilibrium impacts.
2) changing the parameters of the s-curve retirement function. The half-life and steepness in the table I noted above define the trajectory of power plant survival as a function of time.
3) profit-related shutdown. The profit shutdown function is also an s-curve, and its median and steepness are set in the same retirement table noted above. The defaut value of -0.1 means that when the value of the electricity produced is 10% lower than the variable costs of producing power, 50% of the cohort will not operate in the given time period. A policy such as a "coal tax" will lead to shutdown of some portion of the stock.
As @d3y419 noted, this strategy of increasing the costs in order to force early retirement/shutdown of coal is guaranteed to cause equilibrium impacts in the electric sector markets, which may or may not be desired.

**Comment by robbieorvis** [comment]
Okay, this all makes sense.

Thank you both again for your help on this.

The dispatch modeling will be a huge improvement to the representation of the electricity sector, so I'm looking forward to seeing that released.
