### ISSUE TITLE
SEVERE ERROR:Failed to find Java class XMLDBDriver to write to the XML database

### ISSUE THREAD

**Issue by felipefeijoo** [JGCRI/gcam-core#62]
![gcam](https://user-images.githubusercontent.com/7244854/57988010-f5bb9c00-7a56-11e9-98bf-90fc36136b62.png)

I am getting the error "**SEVERE ERROR:Failed to find Java class XMLDBDriver to write to the XML database**." even before GCAM starts solving the model period 1990 (see attached image). GCAM runs fine if I disable the write output to data base option in the configuration file (./db/database_basexdb). I am running on Linux (Debian) and I have JAVA installed:
$ java -version
Picked up _JAVA_OPTIONS: -XX:ParallelGCThreads=2
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

Any ideas?

**Comment by pralitp** [comment]
This is most likely caused by not being able to find the third party Java `jar` files that are required to run the `XMLDBDriver` / add results to the GCAM XML database.  We end up making this check early in the GCAM run to trap such a problem instead of having to wait until the entire scenario runs only to find out you do not have any results.

To debug this you can try running the `XMLDBDriver` independently.  When compiling GCAM you must set the `JARS_LIB` environment variable [described here](http://jgcri.github.io/gcam-doc/gcam-build.html#41-building-with-makefile).

You should use that path in conjunction with the other paths noted at the very bottom of:
http://jgcri.github.io/gcam-doc/user-guide.html

Which describes how to run the `XMLDBDriver` independently.  Once you get that path set properly you will have to recompile GCAM and the issue should be resolved.

**Comment by alexistrejo** [comment]
If it helps anyone, what worked for me was:
+ switch back to jdk 1.8 instead of the operating system default jdk (11) by using JAVA_HOME environment variable.
+ apparently gcam looks for BaseX jars in the path set at compile time by JARS_LIB environment variable. I had to create a symbolic link to the location of the jars at run time.

I'm using gcam v5.3
