### ISSUE TITLE
In Ref to closed issue #77: Levelized costs of electricity via GCAM v5.1.3

### ISSUE THREAD

**Issue by IMA18** [JGCRI/gcam-core#82]
Hi,

I apologize for opening this issue again, but I am still trying to get the real LCOE of technologies with CCS in 2100 without the cost adder.

Following your recommendation, I made three changes on the global reference configuration file and policy file.

I changed ../input/policy/forcing_target_4p5.xml to ../input/policy/carbon_tax_10_5.xml

I set the find-path option to 1. Value name="find-path">1

I changed the tax to 0.01 and applied it to all regions, i.e., not only the US.

When I ran GCAM, I got the following error message:
Starting new scenario: Reference
Tue Nov 12 17:32:16 2019:WARNING:Hector::Logger::printLogHeader: hector version 2.0
Tue Nov 12 17:32:16 2019:WARNING:Hector::Logger::printLogHeader: hector version 2.0
Tue Nov 12 17:32:16 2019:WARNING:Hector::Logger::printLogHeader: hector version 2.0
Using negative-emissions-final-demand wth target-finder without explicitly creating a market for CO2 may hinder solution performance.
Please read in a policy file with a zero tax.
Caloutput read in but no land read in for technology Middle East Corn_ArabianSea_RFD_hi
Caloutput read in but no land read in for technology Middle East Corn_ArabianSea_RFD_lo
Reading advanced target finder configuration file ../input/policy/carbon_tax_10_5.xml
Unrecognized string: world found while parsing policy-target-runner.
Must read in a target value for the policy.

I have attached to this comment the configuration file and policy file too.

[carbon_tax_10_5.txt](https://github.com/JGCRI/gcam-core/files/3848203/carbon_tax_10_5.txt)
[configuration.txt](https://github.com/JGCRI/gcam-core/files/3848204/configuration.txt)

Thank you for your time.
Ibrahim

**Comment by kvcalvin** [comment]
The issue is that your configuration file isn't reading in a policy target file, but does have the "find-path" set to 1. You should move the "../input/policy/carbon_tax_10_5.xml" to the end of the `ScenarioComponents` section of the configuration file and use `forcing_target_4p5.xml` in the top of the file as the <Value name="policy-target-file">. That should get rid of both of the major errors.

**Comment by IMA18** [comment]
Thanks for your feedback. 

Following your suggestions has solved my issue. Nevertheless, GCAM assigns a lower cost to power plants with CCS, e.g., gas CC CCS, than those without CCS (see the attached image). At first, I thought that because of the considered CO2 prices technologies with CCS might become less expensive. After a deeper look, however, I noticed even for earlier years (1990-2015), where the CO2 price is zero, some technologies with CCS are still less expensive. Can you please share with me the rationale behind this issue?

P.S. I found this issue persists even when I do not include the carbon tax file.

![CCS techs](https://user-images.githubusercontent.com/49734658/72282258-2c70a300-3634-11ea-8256-ff780f3948db.JPG)

**Comment by pkyle** [comment]
Good question! What is happening in the base years with the CCS technologies is that the costs printed out are just the levelized capital, fixed O&M, and variable O&M costs. The other components to the cost of these electric generation technologies are fuel, cooling water, and cooling system levelized capital costs. Because these latter cost components are tracked in a separate "pass-through" sector, they aren't included in the total costs that are printed out in years when the technology's output is zero. But this doesn't cause any persistent problems; as soon as these technologies have non-zero output, the price information is reported correctly.

**Comment by IMA18** [comment]
Sounds good. Is the rational provided for later years, e.g., 2100, where CCS technologies are less expensive than those without is due to carbon prices?

Many thanks for your support.

**Comment by pkyle** [comment]
Yes. Reported costs of electric generation technologies include any emissions penalties.
