### ISSUE TITLE
Missing lifetimes in building_det.xml

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-core#83]
Hello, 

It appears that there are no specified lifetimes in building_det.xml, meaning that all building equipment is replaced each model step, if I understand correctly. After speaking with Haewon, it sounds like this is an error, and there are supposed to be lifetimes in that file.

**Comment by pkyle** [comment]
Nice find, Robbie! Note that this only applies to the global buildings model, not to the buildings model of GCAM-USA. I just looked through the archives and from the first version of this buildings module, committed around November 2011, through to the present, the global buildings technologies have never been vintaged, though their costs have always been derived from explicit assumptions of capital costs and average equipment lifetimes.
It's hard to say whether not vintaging this technology group was intentional; I can't find any documentation indicating that it was or wasn't supposed to be included at any specific time. On the one hand, all data assumptions are in place for it to be included; on the other, if you examine the efficiency assumptions in any region/technology, there's no discontinuity between the final historical year and the first future time period, which would be characteristic of an intentional switch from a stock average to new installations.
Going forward, I don't know whether this will be something we look into in the next few months, but if you'd like a version that applies the lifetime assumptions, just let me know off-line and I'll send you a patch.

**Comment by robbieorvis** [comment]
Great, thanks for looking into it! FWIW, over the long run this seems pretty important since it dictates the turnover rate for capital stock in the building sector, with significant implications for decarbonizing that sector.
