### ISSUE TITLE
Missing input/extra/transportation_UCD_SSP[1-5].xml

### ISSUE THREAD

**Issue by simonmoulds** [JGCRI/gcam-core#91]
Running GCAM 5.2 with configuration_ssp.xml, I get the error 'unable to open primary document entity '/path/to/gcam-core/input/extra/transportation_UCD_SSP3.xml'

As the error suggests, I don't have these files in input/extra - they're not shipped with gcam-core. Is it possible to obtain them from somewhere else? 

Thanks a lot for your help.

**Comment by pralitp** [comment]
The transportation_UCD_SSP[1-5].xml is not included in the Git repository because we need to avoid committing large files in the version control system.

They _can_ be generated from the `gcamdata` processing however it is a bit of a pain.  To do so you need to edit `input/gcamdata/R/constants.R` and change on line `349`:
```
# Constant to select SSP database to use for transportation UCD
energy.TRN_SSP <- "CORE"
```

* To `energy.TRN_SSP <- "SSP1"`
* Re-run the data system to build XMLs
* Copy the file from `input/gcamdata/xml/transportation_UCD_SSP1.xml` into `input/extra`
* Repeat for each `SSP2`, `SSP3`, `SSP5` (`SSP4` doesn't exist as it will share with `SSP3`)

Note, each time you run the data system it wipes out **all** XMLs (which is why we copy these to `input/extra` each time) so be sure to keep a backup copy of `transportation_UCD_CORE.xml` unless you want to re-run the data system one more time.

**However, because this is such a pain we do include them in the Windows and Mac Release packages.**  You can just copy them from there instead and save a bunch of time (unless of course you are going to be updating assumptions affecting those files in which case you will have to re-build them from the data system).

**Comment by simonmoulds** [comment]
Thanks Pralit - I'll just copy them from the Windows/Mac release.
