### ISSUE TITLE
Example of modeling Building Energy Service Efficiency Policy.

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcam-core#92]
Hi 

I am interested in modeling building efficiency policies (such as retrofitting program, appliance standard, etc ) in GCAM.  Can someone kindly provide directions on how to generate the XML file for these policies?

Thank you in advance.

**Comment by rjplevin** [comment]
In case anyone is interested, I've recently added to pygcam options to read simple CSV input files to generate various types of policies. These include renewable energy (electricity) standards, building energy standards, and (still in testing) vehicle energy consumption standards.

I haven't documented it very well yet, though I'll do so if there's interest.

**Comment by robbieorvis** [comment]
@RawisWar I have done this for building codes (thermal efficiency) and for appliance standards (equipment efficiency). You have to create XML files that read in like the building_det.xml file with the relevant thermal and equipment efficiency values. You can probably make these files using the GCAM data system, but it would be quite a bit of work. As @rjplevin mentioned, he has a great system for doing this using pygcam that I've used several times and would be happy to follow-up on. Basically you set a percent improvement for certain equipment and his program runs through and modifies efficiency values to give you the desired XML file. 

I have not tried this with retrofitting, but there are a few challenges there, including issues with appliance lifetime and the way GCAM tracks cohorts.

**Comment by robbieorvis** [comment]
Just to circle back on this, I successfully implemented a building electrification policy today in GCAM. However, there is a problem due to a data issue that @pkyle and I discovered about a month back. The core version of GCAM does not have lifetimes nor retirement parameters for buildings (it appears this may have been an oversight) and as a result, the equipment stock in buildings is essentially replaced in each timestep. So if you implement a policy mandating all electric new equipment in buildings, you will affect all of the stock, not just new components. 

This could be resolved if in the next update to GCAM core this data inconsistency is fixed and building equipment assigned lifetimes and retirement parameters (which is a worthwhile improvement in its own right).

**Comment by RawisWar** [comment]
@robbieorvis & @rjplevin thanks for help. I successfully install  pygcam a couple of days ago. 
I am still getting accustom to the interface. I would greatly appreciate any help to run the building energy policy scenarios in pygcam.
Thanks in advance

**Comment by rjplevin** [comment]
I'm in the process of documenting all the new features. Probably easiest to contact me directly: rich@plevin.com.

**Comment by kvcalvin** [comment]
I'm closing this as it seems the initial request has been addressed. @robbieorvis: I think the issue you raise in your last comment is duplicative of https://github.com/JGCRI/gcam-core/issues/83 which I will leave open.
